# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Quote.create(quip: "You are awesome!", author: "Maven")
Quote.create(quip: "Don't compare your beginning to someone else's middle.")
Quote.create(quip: "Decide that you want it more than you are afraid of it.")
Quote.create(quip: "Don't hide from the robots.")
Quote.create(quip: "Happiness is not the absence of problems, it's the ability to deal with them.")
Quote.create(quip: "Creative thinking inspires ideas. Ideas inspire change.")
Quote.create(quip: "Try not to become a man of success. Rather become a man of value.")
Quote.create(quip: "Stop chasing the money and start chasing the passion.")
Quote.create(quip: "Success is walking from failure to failure with no loss of enthusiasm.")
Quote.create(quip: "If you are not willing to risk the usual, you will have to settle for the ordinary.")
Quote.create(quip: "All progress takes place outside the comfort zone.")
Quote.create(quip: "Don't let the fear of losing be greater than the excitement of winning.")
Quote.create(quip: "If you really look closely, most overnight successes took a long time.")
Quote.create(quip: "The only limit to our realization of tomorrow will be our doubts of today.")
Quote.create(quip: "The way to get started is to quit talking and begin doing.")
Quote.create(quip: "Don't be distracted by criticism. Remember--the only taste of success some people get is to take a bite out of you.")
Quote.create(quip: "It is better to fail in originality than to succeed in imitation.")
Quote.create(quip: "Strive not to be a success, but rather to be of value.")
Quote.create(quip: "We become what we think about.")
Quote.create(quip: "Your time is limited, so don’t waste it living someone else’s life.")
Quote.create(quip: "The two most important days in your life are the day you are born and the day you find out why.")
Quote.create(quip: "Either you run the day, or the day runs you.")
Quote.create(quip: "The mind is everything. What you think you become. ")
Quote.create(quip: "Whether you think you can or you think you can’t, you’re right.")
Quote.create(quip: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci")
Quote.create(quip: "It is never too late to be what you might have been.")
Quote.create(quip: "You cannot protect yourself from sadness without protecting yourself from happiness.")
Quote.create(quip: "Smile.")
Quote.create(quip: "Laugh Often.")
Quote.create(quip: "Happiness is not the absence of problems, it's the ability to deal with them.")
