# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7448e684e0d3365fcd848d1ec94a59fc8c08f907f057a58a2d162cb8aa5c3a0f08c2ae211aada81359d24c91df19f970f8d96a69264ed676ac9a9f50d9c7f44a

test:
  secret_key_base: d53425b0ee170a495607c3f89e3e62e8bd30e4d191066381ac22fbd0f750a1d24e94e27b58f62335b96c9c48f785412e1bc167db95c2f5f44c3a2e6f9017f97a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
