# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d67f998956ab4b9e3410ec27380fe039a83be41fc32830c75119ac27b3b8a1550cef9a00dd38c1d58f15bca4cecb7869e7046fd3ec363990a93e3120cde4765f

test:
  secret_key_base: 0fe55c0043e6bdc245a27f2d40645f59c869132aaef181dc2c6517ecbae8fc82124e78eeb99d8741e3938ce520836f4bb96a784f4a531f80bc3f9cd02419e080

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
